name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Minha primeira actions"
        run: echo "Hello World !!!"
      - name: "Segunda acao"
        run: |
          echo "Voce crio o seu primeiro workflow !!!"
          echo "Parabens"
