name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Minha primeira actions"
        run: echo "Hello World !!!"
      - name: "Segunda acao"
        run: |
          echo "Voce crio o seu primeiro workflow !!!"
          echo "Parabens"
  segundo-job:
    name: "Instalacao do ambiente NodeJs"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Verificacao as versao do NodeJs atual"
        run: node --version
      - name: "Definicao da versao 20.13.1 do NodeJs"
      - uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
      - name: "Verificacao as versao do NodeJs depois de instalar"
        run: node --version
        
